sudo: required
services:
  - docker

before_install:
  - docker build -t asnunes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asnunes/react-test npm test

after_success:
  - docker build -t asnunes/multi-client ./client 
  - docker build -t asnunes/multi-nginx ./nginx
  - docker build -t asnunes/multi-server ./server
  - docker build -t asnunes/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push asnunes/multi-client
  - docker push asnunes/multi-nginx
  - docker push asnunes/multi-server
  - docker push asnunes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-071681586584
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY